name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t custom-nginx:latest .

      - name: Save Docker image to tar file
        run: |
          docker save custom-nginx:latest -o custom-nginx.tar
  
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: custom-nginx.tar

  test:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3  
        with:
            name: docker-image

      - name: Load Docker image
        run: |
            docker load -i custom-nginx.tar

      - name: Docker Run container
        run: |
            docker run -d -p 8080:80 --name nginx-container custom-nginx:latest

      - name: Check running container 
        run: |
            docker ps
