name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t custom-nginx:latest .

      - name: Save Docker image to tar file
        run: |
          docker save custom-nginx:latest -o custom-nginx.tar
  
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: custom-nginx.tar
